### ISSUE TITLE
[FR] Add an option in server to pass host to listen

### ISSUE THREAD

**Issue by ogarcia** [tuxlinuxien/lesspassgo#2]
By default now the server is listen to any. Would be great to have a `--host value, -h value  (default: 0.0.0.0) [$HOST]` to set that only listen localhost for example.

Sorry for not send with previous FR, but I'm [packaging your app](https://aur.archlinux.org/packages/lesspassgo-server/) and I am seeing possible features in the way.

**Comment by tuxlinuxien** [comment]
Let me add it now

**Comment by tuxlinuxien** [comment]
Added! But `-h` is already used for `--help` so the current option is can give you is this

`--host value            (default: "0.0.0.0") [$HOST]`

If you are ok with this change, you can close the issue. Also feel free to add new **issues** if you want more features.

**Comment by ogarcia** [comment]
Great!

And yes I forgot the `-h` for `--help`, but with `--host` and `$HOST` environment variable is sufficient.

I go to update the package :wink:
